---
- hosts: all

  user: root

  tasks:
  
  - name: Install s3fs
    apt: name= {{item}} state=present update_cache=yes
    with_items:
      - apt-transport-https
      - curl
      - software-properties-common
      - python
      - python3-pip
      - unzip
      - s3fs
      - awscli

  - name: update
    shell: sudo apt-get update -y



  - name: packages
    shell: sudo apt-get -y install automake autotools-dev fuse g++ git libcurl4-gnutls-dev libfuse-dev libssl-dev libxml2-dev make pkg-config

  - name: Clone a repository
    git:
      repo: 'https://github.com/s3fs-fuse/s3fs-fuse.git'
      version: master
      dest: /root/a
      accept_hostkey: yes

  - name: Install s3fs details - autogen
    shell: cd /root/a && sh /root/a/autogen.sh

  - name: Install s3fs details - configure
    shell: /root/a/configure

  - name: Install s3fs details - make
    shell: cd /root/ %% make

  - name: Install s3fs details - make install
    shell: cd /root/ && sudo make install

  - name: make /mnt/s3 forlder
    file:
      path: /mnt/s3
      state: directory

  - name: Credential into file
    shell: echo 52c829f8b84a4eb4b8591ace181945da:67f3001ee1653507ff1ab28453891a324077b7130a8d8171 > ${HOME}/.passwd-s3fs

  - name: "chmod 600 to ${HOME}/.passwd-s3fs"
    shell: chmod 600 ${HOME}/.passwd-s3fs

  - name: Credential into file
    shell: s3fs iphong /mnt/s3 -o url=http{s}://s3.seo01.cloud-object-storage.appdomain.cloud -o passwd_file=${HOME}/.passwd-s3fs

  - name: server list download 
    shell: wget https://raw.githubusercontent.com/Kylekr/lg-sample/master/1.txt

  - name: mtr script download 
    shell: wget https://raw.githubusercontent.com/Kylekr/lg-sample/master/sample.sh

  - name: execute mtr script
    shell: sh sample.sh




